[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.7"
crossterm = "0.28.1"
enigo = "0.3.0"
local-ip-address = "0.6.3"
rouille = "3.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
